// ═══════════════════════════════════════════════════════════════
//  ESCAPE FROM SAINT-DOMINGUE — GAME DATA
//  Haiti 1791 · CLIL Survival RPG
// ═══════════════════════════════════════════════════════════════

const ABILITIES = [
  { id: 'STR', name: 'Strength',   emoji: '💪', color: '#e05030', desc: 'Physical tasks: climbing, swimming, fighting, carrying' },
  { id: 'DEX', name: 'Dexterity',  emoji: '🐆', color: '#c17817', desc: 'Stealth, speed, moving quietly, dodging patrols' },
  { id: 'CON', name: 'Endurance',  emoji: '🫀', color: '#8B2500', desc: 'Resisting illness, hunger, heat, exhaustion' },
  { id: 'INT', name: 'Intelligence', emoji: '🧠', color: '#1A3A5C', desc: 'Navigation, planning, reading maps, strategy' },
  { id: 'WIS', name: 'Wisdom',     emoji: '🌿', color: '#1C3A1C', desc: 'Medicine, jungle knowledge, reading danger signs' },
  { id: 'CHA', name: 'Charisma',   emoji: '🗣️', color: '#4A3080', desc: 'Persuasion, deception, inspiring your team, storytelling' },
];

const ITEMS = [
  { id: 'map',       name: 'Map of the Island',   emoji: '🗺️', desc: 'Old French map — roads, rivers, military posts.', bonus: 'Navigation: avoid checkpoints, find crossings', abilities: ['INT','WIS'] },
  { id: 'knife',     name: 'A Knife',              emoji: '🔪', desc: 'Small sharp blade from the plantation fields.', bonus: 'Combat & survival: cut rope, hunt, defend', abilities: ['STR','DEX'] },
  { id: 'plants',    name: 'Medicinal Plants',     emoji: '🌿', desc: 'Local plants that treat fever and wounds.', bonus: 'Medicine: malaria, infection, injuries', abilities: ['WIS'] },
  { id: 'rope',      name: 'Rope (10m)',            emoji: '🪢', desc: 'Strong sugar-cane rope from the storehouse.', bonus: 'Utility: cross rivers, climb, tie supplies', abilities: ['STR','DEX'] },
  { id: 'food',      name: 'Food for 3 Days',      emoji: '🍚', desc: 'Cassava bread and dried fruit — heavy but vital.', bonus: 'Nutrition: stay strong for the journey', abilities: ['CON'] },
  { id: 'water',     name: 'Water Gourd',          emoji: '💧', desc: 'Large gourd holding ~2 litres.', bonus: 'Hydration: survive heat without stopping', abilities: ['CON','WIS'] },
  { id: 'flint',     name: 'Flint & Steel',        emoji: '🔥', desc: 'Make fire even in the rain.', bonus: 'Fire: warmth, cooking, signalling allies', abilities: ['WIS','INT'] },
  { id: 'letter',    name: 'Stolen Letter',        emoji: '📖', desc: 'Letter in French from an owner to a general.', bonus: 'Deception: pose as a messenger', abilities: ['CHA','INT'] },
  { id: 'clothes',   name: 'Dark Clothing',        emoji: '🌑', desc: 'Black cloth to cover body and face.', bonus: 'Stealth: move unseen at night', abilities: ['DEX'] },
  { id: 'drum',      name: 'A Drum',               emoji: '⚱️', desc: 'Small ceremonial drum — heavy, meaningful.', bonus: 'Signal & morale: communicate with rebels', abilities: ['CHA','WIS'] },
  { id: 'jungle',    name: 'Jungle Knowledge',     emoji: '🐾', desc: 'One person knows every jungle path.', bonus: '+3 to all jungle events', abilities: ['WIS','DEX'] },
  { id: 'quinine',   name: 'Quinine Powder',       emoji: '💊', desc: 'Medicine against malaria — one use only.', bonus: 'Survive jungle fever (one use)', abilities: ['WIS','CON'] },
  { id: 'lantern',   name: 'Oil Lantern',          emoji: '🔦', desc: 'Dim light — useful but visible from far.', bonus: 'Navigate at night — BUT soldiers may see', abilities: ['INT'] },
  { id: 'shoes',     name: 'Good Shoes',           emoji: '👟', desc: 'Strong leather shoes — rare for slaves.', bonus: 'Move faster, avoid rocky path injuries', abilities: ['CON','STR'] },
  { id: 'key',       name: 'A Stolen Key',         emoji: '🗝️', desc: 'Opens a locked gate on the mountain road.', bonus: 'Unlock one checkpoint — no fighting needed', abilities: ['INT','CHA'] },
  { id: 'papers',    name: 'Forged Freedom Papers',emoji: '📜', desc: 'Badly forged document claiming you are free.', bonus: 'Might fool a tired soldier — risky!', abilities: ['CHA'] },
  { id: 'machete',   name: 'A Machete',            emoji: '🎋', desc: 'Large blade for cutting jungle vegetation.', bonus: 'Move faster through thick jungle', abilities: ['STR','DEX'] },
  { id: 'thread',    name: 'Needle & Thread',      emoji: '🧵', desc: 'Small sewing kit from the plantation house.', bonus: 'Repair clothing, close wounds, bandages', abilities: ['WIS','DEX'] },
  { id: 'seeds',     name: 'Seeds',                emoji: '🌾', desc: 'Handful of seeds from the garden.', bonus: 'Plant food when you arrive (useless en route)', abilities: ['WIS'] },
  { id: 'conch',     name: 'Conch Shell',          emoji: '📣', desc: 'Sea shell that makes a loud sound.', bonus: 'Warn allies — BUT soldiers can hear it too', abilities: ['CHA','WIS'] },
];

// D20 roll result categories
const ROLL_OUTCOMES = [
  { min: 20, max: 20, label: 'NATURAL 20 ✨', color: '#FFD700', tokens: +3, narrative: 'LEGENDARY! Your action becomes the stuff of legend among the rebels. Every team gains 1 bonus token.' },
  { min: 16, max: 19, label: 'Great Success!', color: '#2ecc71', tokens: +2, narrative: 'Excellent. Your skill and courage shine. The team pushes forward with confidence.' },
  { min: 11, max: 15, label: 'Success',        color: '#a8e670', tokens: +1, narrative: 'It works. Not perfectly, but well enough. You survive this challenge.' },
  { min:  6, max: 10, label: 'Partial Fail',   color: '#e67e22', tokens:  0, narrative: 'Close — but not quite. You get through, but at a cost. No tokens gained.' },
  { min:  2, max:  5, label: 'Fail',           color: '#e74c3c', tokens: -1, narrative: 'Things go wrong. You lose precious time, supplies, or safety.' },
  { min:  1, max:  1, label: 'CRITICAL FAIL 💀', color: '#8B0000', tokens: -2, narrative: 'DISASTER. The worst possible outcome. Something terrible happens to your group.' },
];

// Severity from D6
const SEVERITY = [
  null, // index 0 unused
  { label: 'Mild',     color: '#a8e670', modifier: 0,  desc: 'The danger is manageable.' },
  { label: 'Mild',     color: '#a8e670', modifier: 0,  desc: 'The danger is manageable.' },
  { label: 'Moderate', color: '#e67e22', modifier: -1, desc: 'The situation is serious.' },
  { label: 'Moderate', color: '#e67e22', modifier: -1, desc: 'The situation is serious.' },
  { label: 'Severe',   color: '#e74c3c', modifier: -2, desc: 'This is extremely dangerous.' },
  { label: 'Severe',   color: '#e74c3c', modifier: -2, desc: 'This is extremely dangerous.' },
];

// D20 EVENTS TABLE
const EVENTS = [
  {
    id: 1, d20: 1,
    title: '🌊 The River',
    subtitle: 'A fast river blocks your path',
    description: 'The river is 20 metres wide and 2 metres deep. The current is strong. There is no bridge — or the bridge is guarded.',
    question: 'How do your team cross the river safely?',
    goodItems: ['rope', 'map', 'shoes', 'machete'],
    goodAbilities: ['STR', 'DEX', 'INT'],
    severeMild: 'The river is calm enough to wade.',
    severeHard: 'Flash flood — the water is violent and rising fast.',
  },
  {
    id: 2, d20: 2,
    title: '💂 Soldiers at the Checkpoint',
    subtitle: 'French soldiers are checking everyone',
    description: 'A group of armed soldiers stands on the road ahead. They are checking papers and searching bags. There are 6 of them.',
    question: 'How do you get past the soldiers without being captured?',
    goodItems: ['clothes', 'papers', 'letter', 'key', 'map'],
    goodAbilities: ['DEX', 'CHA', 'INT'],
    severeMild: 'The soldiers look tired and bored — one is asleep.',
    severeHard: 'The soldiers are alert and searching everyone very carefully.',
  },
  {
    id: 3, d20: 3,
    title: '🤒 Fever in the Night',
    subtitle: 'Malaria strikes your team',
    description: 'Three members of your team wake up shaking with fever. Their skin is burning. If untreated, they cannot walk by morning.',
    question: 'How do you treat the sick team members and keep moving?',
    goodItems: ['plants', 'quinine', 'water', 'food'],
    goodAbilities: ['WIS', 'CON', 'INT'],
    severeMild: 'Only one person is ill — the others are fine.',
    severeHard: 'Four people are ill and one is delirious, making noise.',
  },
  {
    id: 4, d20: 4,
    title: '🌑 Lost in the Dark',
    subtitle: 'The moon disappears. You are going in circles.',
    description: 'Clouds cover the moon. The jungle is completely black. You have walked for one hour and are back where you started.',
    question: 'How do you find your direction without being seen?',
    goodItems: ['flint', 'lantern', 'map', 'jungle'],
    goodAbilities: ['INT', 'WIS', 'DEX'],
    severeMild: 'You can still see the stars in one direction.',
    severeHard: 'You can hear dogs barking behind you — soldiers are tracking you.',
  },
  {
    id: 5, d20: 5,
    title: '🏔️ The Mountain Climb',
    subtitle: 'Steep rocks. Someone is hurt.',
    description: 'The path to the mountain camp goes up a sheer rocky cliff. One team member slips and twists their ankle badly.',
    question: 'How do you get everyone up the cliff and keep the injured person safe?',
    goodItems: ['rope', 'shoes', 'knife', 'thread'],
    goodAbilities: ['STR', 'CON', 'WIS'],
    severeMild: 'The slope is steep but there are good hand-holds.',
    severeHard: 'The injured person cannot put any weight on their foot at all.',
  },
  {
    id: 6, d20: 6,
    title: '🐾 Ambush in the Jungle',
    subtitle: 'Bounty hunters are waiting',
    description: 'People paid to recapture escaped slaves are hiding on the path. They jump out suddenly — there are four of them.',
    question: 'How do you escape or defeat the bounty hunters?',
    goodItems: ['knife', 'machete', 'jungle', 'map', 'conch'],
    goodAbilities: ['STR', 'DEX', 'WIS'],
    severeMild: 'The bounty hunters are on foot with no weapons except sticks.',
    severeHard: 'The bounty hunters are armed and have a horse.',
  },
  {
    id: 7, d20: 7,
    title: '⛈️ Tropical Storm',
    subtitle: 'The heavens open',
    description: 'A violent tropical storm hits. Rain so heavy you cannot see. Lightning every few seconds. The path becomes a mudslide.',
    question: 'How does your team survive the storm and keep moving?',
    goodItems: ['rope', 'clothes', 'flint', 'machete', 'map'],
    goodAbilities: ['CON', 'WIS', 'STR'],
    severeMild: 'The storm lasts only 20 minutes.',
    severeHard: 'The storm lasts all night. Someone is struck by a falling branch.',
  },
  {
    id: 8, d20: 8,
    title: '🧑‍🤝‍🧑 Other Escapees',
    subtitle: 'Four strangers appear from the dark',
    description: 'Four more enslaved people stumble into your path — cold, hungry, and lost. They are not from your plantation. They beg to join you.',
    question: 'Do you take them? If yes, how do you manage with more people and fewer resources?',
    goodItems: ['food', 'water', 'conch', 'map'],
    goodAbilities: ['CHA', 'WIS', 'CON'],
    severeMild: 'The strangers are healthy and have a small knife of their own.',
    severeHard: 'One of the strangers has a bullet wound and cannot run.',
  },
  {
    id: 9, d20: 9,
    title: '🥁 The Drum Call',
    subtitle: 'Rhythms from the mountains',
    description: 'You hear drums from the mountains — complex rhythms. It is the revolutionary camp sending a signal. But what does it mean?',
    question: 'How do you interpret the drums, and do you respond?',
    goodItems: ['drum', 'conch', 'jungle'],
    goodAbilities: ['WIS', 'CHA', 'INT'],
    severeMild: 'The rhythm is simple — it means "come this way".',
    severeHard: 'The rhythm is complex and urgent — it might mean "danger ahead".',
  },
  {
    id: 10, d20: 10,
    title: '🐕 Plantation Dogs',
    subtitle: 'You can hear them getting closer',
    description: 'The slavers have released trained dogs to track you. You can hear barking in the distance — and it is getting louder.',
    question: 'How do you lose the dogs and stop them tracking your scent?',
    goodItems: ['map', 'jungle', 'water', 'clothes', 'machete'],
    goodAbilities: ['DEX', 'WIS', 'INT'],
    severeMild: 'The dogs are far away — you have 20 minutes.',
    severeHard: 'The dogs are very close. You can see torch light behind you.',
  },
  {
    id: 11, d20: 11,
    title: '🌅 Dawn Is Coming',
    subtitle: 'You must hide before daylight',
    description: 'The sky is turning grey. In one hour it will be light. You are still in open land — visible from the road. Soldiers patrol at sunrise.',
    question: 'How do you find shelter and hide your whole group before dawn?',
    goodItems: ['machete', 'map', 'clothes', 'jungle', 'rope'],
    goodAbilities: ['INT', 'DEX', 'WIS'],
    severeMild: 'There is a sugar cane field nearby — dense cover.',
    severeHard: 'The land is open. The nearest jungle is 2km away.',
  },
  {
    id: 12, d20: 12,
    title: '👶 The Crying Baby',
    subtitle: 'Silence is survival',
    description: 'One team member has a baby wrapped against her chest. The baby begins to cry loudly — soldiers are only 200 metres away.',
    question: 'How do you keep the baby quiet and keep the family together safely?',
    goodItems: ['food', 'water', 'clothes', 'plants'],
    goodAbilities: ['CHA', 'WIS', 'CON'],
    severeMild: 'The soldiers seem distracted by something ahead of them.',
    severeHard: 'The soldiers have stopped and are looking directly toward you.',
  },
  {
    id: 13, d20: 13,
    title: '⚔️ Deserter Soldier',
    subtitle: 'A French soldier approaches alone — hands raised',
    description: 'A young French soldier stumbles out of the jungle, alone, terrified. He says he deserted his unit. He says he wants to help you. Do you trust him?',
    question: 'Do you trust the soldier? How do you handle this situation?',
    goodItems: ['knife', 'letter', 'map', 'papers'],
    goodAbilities: ['CHA', 'WIS', 'INT'],
    severeMild: 'The soldier is young — 16 years old — and clearly afraid.',
    severeHard: 'You cannot tell if he is genuine or a spy sent to find your route.',
  },
  {
    id: 14, d20: 14,
    title: '💔 Betrayal',
    subtitle: 'Someone in the group is slowing you down',
    description: 'An argument breaks out. One team member wants to go back — they are too tired and too frightened. They are threatening to make noise.',
    question: 'How do you keep your team united and moving?',
    goodItems: ['food', 'water', 'drum', 'conch'],
    goodAbilities: ['CHA', 'WIS', 'CON'],
    severeMild: 'The person is scared but still rational and can be reasoned with.',
    severeHard: 'The person sits down and refuses to move. Time is running out.',
  },
  {
    id: 15, d20: 15,
    title: '🍌 Hidden Food Cache',
    subtitle: 'Someone left supplies in the jungle',
    description: 'You find a hollow tree trunk with food, fresh water, and a small handwritten note in Haitian Creole. Someone left this for escapees.',
    question: 'How do you use this gift? What does it mean for your team\'s morale?',
    goodItems: ['map', 'jungle', 'drum'],
    goodAbilities: ['WIS', 'INT', 'CHA'],
    severeMild: 'The cache has enough food for three days and a simple map.',
    severeHard: 'The food is there but the note says "soldiers know about this path — go another way".',
  },
  {
    id: 16, d20: 16,
    title: '🌊 The Flooded Bridge',
    subtitle: 'The only bridge is underwater',
    description: 'The rainy season has flooded the river. The bridge you needed is 3 metres underwater. Your map shows no alternative crossing.',
    question: 'How does your team find or create another way across?',
    goodItems: ['rope', 'machete', 'map', 'jungle', 'knife'],
    goodAbilities: ['STR', 'INT', 'WIS'],
    severeMild: 'The river is wide but shallow — perhaps only 1 metre deep.',
    severeHard: 'The river is 3 metres deep and the current is violent.',
  },
  {
    id: 17, d20: 17,
    title: '🔥 The Plantation is Burning',
    subtitle: 'Fire and chaos everywhere',
    description: 'A nearby plantation is on fire. Explosions. Screaming. The flames light up the sky — you can be seen for miles. But the soldiers are distracted.',
    question: 'Do you use the chaos as cover, or do you wait? How do you move through smoke and fire?',
    goodItems: ['map', 'clothes', 'water', 'jungle'],
    goodAbilities: ['DEX', 'INT', 'CON'],
    severeMild: 'The fire is moving away from you.',
    severeHard: 'The wind is blowing the fire in your direction. You have minutes.',
  },
  {
    id: 18, d20: 18,
    title: '🐊 River Monster',
    subtitle: 'Something is in the water',
    description: 'You reach the river. As the first person enters the water — they scream. Crocodiles. Two of them, lurking in the shallows.',
    question: 'How do you cross the river safely with crocodiles in the water?',
    goodItems: ['knife', 'machete', 'rope', 'flint', 'conch'],
    goodAbilities: ['STR', 'WIS', 'DEX'],
    severeMild: 'The crocodiles are on the far bank — the entry point is clear.',
    severeHard: 'Both crocodiles are between your team and the other side.',
  },
  {
    id: 19, d20: 19,
    title: '⭐ The Mountain Camp Lights',
    subtitle: 'You can see fires above you',
    description: 'On the mountain ahead you see small fires — the camp of the revolution. You are close. But between you and the lights: one final heavily-guarded road.',
    question: 'You are so close. How does your team make the final push to freedom?',
    goodItems: ['map', 'clothes', 'key', 'papers', 'jungle', 'conch'],
    goodAbilities: ['DEX', 'CHA', 'WIS'],
    severeMild: 'Only two soldiers guard the road, and they look half-asleep.',
    severeHard: 'A full patrol of 12 soldiers is marching up and down the road.',
  },
  {
    id: 20, d20: 20,
    title: '🔱 BOUKMAN\'S SPIRIT',
    subtitle: '⚡ LEGENDARY EVENT — all teams participate',
    description: '"Do not forget that God who created the sun watches over us from the clouds. He sees all the white has done. The God of the white asks crimes of him, but our God asks good works of us. Listen to liberty that speaks in the hearts of all of us." — Dutty Boukman, 1791',
    question: 'Every team: what does FREEDOM mean to you? Say it in English. Every answer gets full tokens.',
    goodItems: ['drum', 'conch', 'plants', 'seeds'],
    goodAbilities: ['CHA', 'WIS', 'CON'],
    severeMild: 'All teams speak. No dice needed.',
    severeHard: 'All teams speak. No dice needed.',
    legendary: true,
  },
];

window.GAME_DATA = { ABILITIES, ITEMS, EVENTS, SEVERITY, ROLL_OUTCOMES };
